pluginManagement {
    repositories {
        gradlePluginPortal()
        google()
        mavenCentral()
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        maven { url "https://jitpack.io" }
        //noinspection JcenterRepositoryObsolete
        jcenter()
    }
}
rootProject.name = "Griya Kampung"
include ':app'
include ':domain'
include ':data'
include ':data:local'
include ':data:remote'
include ':presentation'
include ':data:remote-backup'
