plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
    id 'org.jetbrains.kotlin.kapt'
    id 'com.google.dagger.hilt.android'
    id 'com.google.gms.google-services'
}

android {
    signingConfigs {
        debug {
            storeFile file(STORE_FILE)
            storePassword STORE_PASSWORD
            keyAlias STORE_KEY_ALIAS
            keyPassword STORE_KEY_PASSWORD
        }

        release {
            storeFile file(STORE_FILE)
            storePassword STORE_PASSWORD
            keyAlias STORE_KEY_ALIAS
            keyPassword STORE_KEY_PASSWORD
        }
    }
    namespace 'net.bagusekasaputra.griyakampoengtkw'
    compileSdk 33

    // Increase versionCode as Build process occur
    def versionPropsFile = file('version.properties')
    if (versionPropsFile.canRead()) {
        def Properties versionProps = new Properties()
        versionProps.load(new FileInputStream(versionPropsFile))

        def appVersionCode = versionProps['APP_VERSION_CODE'].toInteger()
        def stableVersionName = versionProps['STABLE_VERSION_NAME']
        def developerVersionName = versionProps['DEVELOPER_VERSION_NAME']

        flavorDimensions 'distribution'
        productFlavors {
            stable {
                applicationId "net.bagusekasaputra.griyakampoengtkw.stable"
                dimension 'distribution'
                versionName stableVersionName
                versionCode appVersionCode
                signingConfig signingConfigs.release
            }
            developer {
                applicationId "net.bagusekasaputra.griyakampoengtkw.developer"
                dimension 'distribution'
                versionName developerVersionName
                versionCode appVersionCode
                signingConfig signingConfigs.debug
            }
        }

        defaultConfig {
            applicationId "net.bagusekasaputra.griyakampoengtkw"
            minSdk 21
            targetSdk 33

            versionCode appVersionCode

            testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
            signingConfig signingConfigs.debug
        }

        def List<String> executedTasks = gradle.startParameter.taskNames
        if (executedTasks.contains("assembleDeveloperRelease") ||
            executedTasks.contains("assembleStableRelease")) {
            println(">> Detected attempt to build Release! Increasing the Version Code now ...")

            versionProps['APP_VERSION_CODE'] = (appVersionCode + 1).toString()
            versionProps['DEVELOPER_VERSION_NAME'] = developerVersionName
            versionProps['STABLE_VERSION_NAME'] = stableVersionName

            // Save file
            versionProps.store(versionPropsFile.newWriter(), null)
            println(">> Version Code has been updated!")
        }

    } else {
        throw new GradleException("Could not read version.properties!")
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    // Automatically name the apk to to the "<AppName>-v<VersionName>(<VersionCode>).apk" format
    android.applicationVariants.all { variant ->
        variant.outputs.each { output ->
            def String flavorName
            if (variant.getFlavorName() == "developer") {
                flavorName = "dev"
            } else {
                flavorName = variant.getFlavorName()
            }

            def fileName = "GriyaKampoengTKW_v${variant.versionName}(${variant.versionCode})-${flavorName}"
            def buildType = variant.buildType.name
            def String outputName
            if (buildType != "release") {
                outputName = fileName + "-" + buildType
            } else {
                outputName = fileName
            }

            output.outputFileName = outputName + ".apk"
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    // kotlinOptions {
    //     jvmTarget = '1.8'
    // }
    buildFeatures {
        viewBinding true
    }
}

dependencies {

    implementation project(path: ':domain')
    implementation project(path: ':data')
    implementation project(path: ':data:local')
    implementation project(path: ':data:remote')
    implementation project(path: ':data:backup')
    implementation project(path: ':presentation')

    implementation 'androidx.core:core-ktx:1.7.0'
    implementation 'androidx.appcompat:appcompat:1.5.1'
    implementation 'com.google.android.material:material:1.7.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test.ext:junit:1.1.3'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.4.0'

    implementation "androidx.preference:preference-ktx:1.2.0"

    implementation 'com.google.dagger:hilt-android:2.44'
    kapt 'com.google.dagger:hilt-compiler:2.44'

    implementation 'androidx.room:room-ktx:2.4.3'
    implementation 'androidx.room:room-runtime:2.4.3'
    kapt 'androidx.room:room-compiler:2.4.3'

    implementation 'androidx.biometric:biometric:1.1.0'

    implementation 'com.google.firebase:firebase-database-ktx:20.0.6'
    implementation 'com.google.firebase:firebase-storage-ktx:20.1.0'

    implementation 'net.lingala.zip4j:zip4j:2.11.5'
    implementation 'com.github.atwa:filepicker:1.0.7'
    implementation 'commons-io:commons-io:2.11.0'

    implementation 'androidx.swiperefreshlayout:swiperefreshlayout:1.1.0'
}
